"""add columns to User table

Revision ID: 80b311e3fae6
Revises: 8480c0e21964
Create Date: 2026-01-18 17:16:18.052376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80b311e3fae6"
down_revision: Union[str, Sequence[str], None] = "8480c0e21964"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("date_of_birth", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("User", sa.Column("phone_number", sa.UnicodeText(), nullable=True))
    op.add_column("User", sa.Column("country", sa.UnicodeText(), nullable=True))
    op.add_column("User", sa.Column("gender", sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "gender")
    op.drop_column("User", "country")
    op.drop_column("User", "phone_number")
    op.drop_column("User", "date_of_birth")
    # ### end Alembic commands ###
