"""add_skill_execution_artifact_table

Revision ID: b5c7d6528e1c
Revises: e1c3f7a2b9d5
Create Date: 2026-04-17 17:14:50.214597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c7d6528e1c'
down_revision: Union[str, Sequence[str], None] = 'e1c3f7a2b9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SkillExecutionArtifact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('sandbox_index', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.UnicodeText(), nullable=False),
    sa.Column('blob_path', sa.UnicodeText(), nullable=False),
    sa.Column('content_type', sa.UnicodeText(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ConversationMessage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['AgentSkill.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SkillExecutionArtifact_conversation_id'), 'SkillExecutionArtifact', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_SkillExecutionArtifact_id'), 'SkillExecutionArtifact', ['id'], unique=False)
    op.create_index(op.f('ix_SkillExecutionArtifact_message_id'), 'SkillExecutionArtifact', ['message_id'], unique=False)
    op.create_index(op.f('ix_SkillExecutionArtifact_skill_id'), 'SkillExecutionArtifact', ['skill_id'], unique=False)
    op.create_index(op.f('ix_SkillExecutionArtifact_user_id'), 'SkillExecutionArtifact', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SkillExecutionArtifact_user_id'), table_name='SkillExecutionArtifact')
    op.drop_index(op.f('ix_SkillExecutionArtifact_skill_id'), table_name='SkillExecutionArtifact')
    op.drop_index(op.f('ix_SkillExecutionArtifact_message_id'), table_name='SkillExecutionArtifact')
    op.drop_index(op.f('ix_SkillExecutionArtifact_id'), table_name='SkillExecutionArtifact')
    op.drop_index(op.f('ix_SkillExecutionArtifact_conversation_id'), table_name='SkillExecutionArtifact')
    op.drop_table('SkillExecutionArtifact')
    # ### end Alembic commands ###
