"""init

Revision ID: cebefe04d044
Revises:
Create Date: 2026-01-10 01:33:58.396774

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cebefe04d044"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.UnicodeText(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("full_name", sa.UnicodeText(), nullable=True),
        sa.Column("username", sa.UnicodeText(), nullable=True),
        sa.Column("first_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_User_deleted"), "User", ["deleted"], unique=False)
    op.create_index(op.f("ix_User_email"), "User", ["email"], unique=True)
    op.create_index(op.f("ix_User_id"), "User", ["id"], unique=False)
    op.create_index(op.f("ix_User_username"), "User", ["username"], unique=True)
    op.create_table(
        "Token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.UnicodeText(), nullable=False),
        sa.Column("token_type", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Token_id"), "Token", ["id"], unique=False)
    op.create_index(
        "token_idx_token",
        "Token",
        ["token", "token_type"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("token_idx_token", table_name="Token", postgresql_using="btree")
    op.drop_index(op.f("ix_Token_id"), table_name="Token")
    op.drop_table("Token")
    op.drop_index(op.f("ix_User_username"), table_name="User")
    op.drop_index(op.f("ix_User_id"), table_name="User")
    op.drop_index(op.f("ix_User_email"), table_name="User")
    op.drop_index(op.f("ix_User_deleted"), table_name="User")
    op.drop_table("User")
    # ### end Alembic commands ###
